[package]
name = "adventofcode2016"
version = "0.1.0"
authors = ["Matthew Lynch <mslynch95@gmail.com>"]

[dependencies]
clap = "2.32.0"
im = "12.3.4"
itertools = "0.9.0"
maplit = "1.0.1"
fancy-regex = "0.2.0"
rpds = "0.6.0"
md5 = "0.7.0"
rust-crypto = "0.2.36"

[lib]
name = "adventofcode2016"
